In [1]:
x = [1,2,3,4,5,6,7]
print(sum(x))

28


In [5]:
def myfunc_1(*args):
    ''' This function return even number from a list'''
    mylist = []
    for num in args:
        if num % 2 == 0:
            mylist.append(num)
    return mylist
            
myfunc_1(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [13]:
def myfunc(my_string):
    ''' This function takes a string and return a matching string where every
        even letter is uppercase, and odd letter is lowercase. '''
    new_string = ''
    lenth_string = len(my_string)
    for letter in range(1,lenth_string+1):
        if letter % 2 == 0:
            new_string = new_string + my_string[letter-1].upper()
        else:
            new_string = new_string + my_string[letter-1].lower()
    
    return new_string

In [14]:
myfunc('Paralelepipedo')

'pArAlElEpIpEdO'

In [16]:
texto = 'Djair Sobral'
mylist = texto.split()
print(mylist)

['Djair', 'Sobral']


In [17]:
mylist[0]

'Djair'

In [18]:
mylist[0][0]

'D'

In [21]:
def myfunc(my_string):
    ''' This function capitalizes the first and fourth letters of a name. '''
    new_string = ''
    lenth_string = len(my_string)
    for letter in range(0,lenth_string):
        if letter == 0 or letter == 3:
            new_string = new_string + my_string[letter].upper()
        else:
            new_string = new_string + my_string[letter].lower()
    
    return new_string

In [22]:
myfunc('macdonald')

'MacDonald'

In [32]:
def master_yoda(text):
    ''' This functrion return a sentence with the words reversed'''
    
    mylist = text.split()
    list_count=len(mylist)
    new_text=[]
    while list_count > 0:
        list_count-= 1
        new_text.append(mylist[list_count])
    print(' '.join(new_text))

In [33]:
master_yoda('Djair Candido Sobral')

Sobral Candido Djair


In [34]:
master_yoda('Sunday Monday Tuesday Wednsday Thursday Friday Saturday')

Saturday Friday Thursday Wednsday Tuesday Monday Sunday


In [65]:
def has_33(nums):
    ''' Given a list of ints, return True if the array contains a 3 next to a 3 somewhere. '''
    flag=0
    index=0
    l=len(nums)
    while index <= l-2:
        if nums[index] == 3 and nums[index+1] == 3:
            index+=1
            flag = 1
        else:
            index+=1
            pass
    if flag == 1:
        return True
    else:
        return False

In [66]:
has_33([1, 3, 3])

True

In [67]:
has_33([1, 3, 1, 3])

False

In [72]:
has_33([1,3,1,3,3,1,3])

True

In [74]:
has_33([1,1,1,3,1,3,1,3,1,3,1])

False

In [36]:
def paper_doll(text):
    new_text=''
    
    for x in range(0,len(text)):
        new_text = new_text+text[x]*3
    return new_text

In [37]:
paper_doll('Mississippi')

'MMMiiissssssiiissssssiiippppppiii'

In [75]:
import numpy as np

In [76]:
lista = [1,2,3,4,5]
a = np.array(lista)
print(a)

[1 2 3 4 5]


In [77]:
a.ndim

1

In [78]:
a.size

5

In [98]:
lista_1 = [(1,2,3),(4,5,6),(7,8,9),('A','B','C')]
a = np.array(lista_1)
lista_2 =[(1,2,3),[4,5,6],(7,8,9)]
b = np.array(lista_2)
#print(a,'\n')
#print(b)
print(a,'\n\n',b)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['A' 'B' 'C']] 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [99]:
print(a.ndim)
print(a.shape)
print(a.size)

2
(4, 3)
12


In [100]:
print(b.ndim)
print(b.shape)
print(b.size)

2
(3, 3)
9


In [108]:
x = np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [109]:
x.ndim

2

In [110]:
x=[1,2,3]
y=[4,5,6]
z=np.array(x+y)

In [111]:
print(z)

[1 2 3 4 5 6]


In [115]:
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [118]:
# The 'arange()' function generate NumPy arrays with numerical sequences.
a = list(np.arange(0,10,0.5))
print(a)

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5]


In [120]:
# The 'reshape()' function divides a linear array in different parts in the manner specified by the shape argument.
np.arange(0,10,0.5).reshape(5,4)

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5],
       [6. , 6.5, 7. , 7.5],
       [8. , 8.5, 9. , 9.5]])

In [121]:
np.arange(0,10,0.5).reshape(4,5)

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [122]:
np.arange(0,10,0.5).reshape(2,10)

array([[0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]])

In [156]:
def blackjack(a,b,c):
    ''' BLACKJACK: Given three integers between 1 and 11, if their sum is less than or 
        equal to 21, return their sum. If their sum exceeds 21 and there's an eleven, 
        reduce the total sum by 10. Finally, if the sum (even after adjustment) exceeds 21, return "BUST" '''
    sum0 = a+b+c
    if sum0 <=21:
        return sum0
    elif sum0>21 and a==11 or b==1 or c==11:
        return sum0-10
    else:
        print('BUST')

In [157]:
blackjack(5,6,7)

18

In [158]:
blackjack(9,9,9)

BUST


In [159]:
blackjack(9,9,11)

19

In [165]:
def summer_69(arr):
    """ SUMMER OF '69: Return the sum of the numbers in the array, except ignore sections
        of numbers starting with a 6 and extending to the next 9 (every 6 will be followed 
        by at least one 9). Return 0 for no numbers."""
    ts = 0
    for num in arr:
        if num >=6 and num<=9:
            pass
        else:
            ts=ts+num
    return ts

In [166]:
summer_69([1, 3, 5])

9

In [167]:
summer_69([4, 5, 6, 7, 8, 9])

9

In [168]:
summer_69([2, 1, 6, 9, 11])

14

In [185]:
def spy_game(nums):
    """ SPY GAME: Write a function that takes in a list of integers and returns True if it contains 007 in order """
    mystring=''
    for num in nums:
        if num == 0:
            if mystring == '00' or mystring == '007':
                pass
            else:
                mystring=mystring+str(num)
        if num == 7:
            if mystring == '007':
                pass
            else:
                mystring=mystring+str(num)
         
    if mystring == '007':
        return True
    else:
        return False

In [186]:
spy_game([1,2,4,0,0,7,5])

True

In [187]:
spy_game([1,0,2,4,0,5,7])

True

In [188]:
spy_game([1,7,2,0,4,5,0])

False

In [213]:
def count_primes(num):
    """ COUNT PRIMES: Write a function that returns the number of 
        prime numbers that exist up to and including a given number""" 
    count=0
    for x in range(num):
       
        if x%2==0 or x%3==0 or x%5==0:
            pass
        else:
            count+=1
    print(f'Total amount of prime numbers: {count-1}')

In [214]:
count_primes(100)

Total amount of prime numbers: 25


In [258]:
##################################################
#d = {'a':('  *',' * *','*****','*   *','*   *'),'b':('*****','*****','***','*****','*****'),'c':('*****','**','**','**','*****')}

In [259]:
def print_big(key):
    d = {'a':('  *',' * *','*****','*   *','*   *'),'b':('*****','*****','***','*****','*****'),'c':('*****','**','**','**','*****')}
    for y in range(5):
        print(d[key][y])

In [260]:
print_big('a')

  *
 * *
*****
*   *
*   *


In [261]:
print_big('c')

*****
**
**
**
*****


In [262]:
print_big('b')

*****
*****
***
*****
*****
